const fs = require('fs');

const filepath = 'c:\\Users\\hp\\Downloads\\DOCEASE\\medicament 1.json';
const data = JSON.parse(fs.readFileSync(filepath, 'utf8'));

// Common keys and values that are often split by spaces
const corrections = [
    [/timin g/g, 'timing'],
    [/ta blet/g, 'tablet'],
    [/form ulation/g, 'formulation'],
    [/indic ation/g, 'indication'],
    [/contraindi cation/g, 'contraindication'],
    [/contraindi cations/g, 'contraindications'],
    [/interactions/g, 'interactions'], // check if split
    [/activeSub stances/g, 'activeSubstances'],
    [/produ ctType/g, 'productType'],
    [/dataS tatus/g, 'dataStatus'],
    [/conc entration/g, 'concentration'],
    [/stre ngth/g, 'strength'],
    [/admin istra tion/g, 'administration'],
    [/administra tion/g, 'administration'],
    [/instru ctions/g, 'instructions'],
    [/pregnan cy/g, 'pregnancy'],
    [/pregna ncy/g, 'pregnancy'],
    [/p regnancy/g, 'pregnancy'],
    [/breastf eeding/g, 'breastfeeding'],
    [/breastfe eding/g, 'breastfeeding'],
    [/special ist/g, 'specialist'],
    [/proto col/g, 'protocol'],
    [/do sing/g, 'dosing'],
    [/po pulation/g, 'population'],
    [/medici ne/g, 'medicine'],
    [/suspen sion/g, 'suspension'],
    [/cap sule/g, 'capsule'],
    [/efferv escent/g, 'effervescent'],
    [/ointment/g, 'ointment'], // check if split
    [/suppos itory/g, 'suppository'],
    [/hypert ension/g, 'hypertension'],
    [/inflamm ation/g, 'inflammation'],
    [/di abetes/g, 'diabetes'],
    [/an tibiotic/g, 'antibiotic'],
    [/cephalo sporin/g, 'cephalosporin'],
    [/paracet amol/g, 'paracetamol'],
    [/diclofen ac/g, 'diclofenac'],
    [/ibupro fen/g, 'ibuprofen'],
    [/amoxic illin/g, 'amoxicillin'],
    [/captop ril/g, 'captopril'],
    [/clonid ine/g, 'clonidine'],
    [/cispla tin/g, 'cisplatin'],
    [/mycophenolate/g, 'mycophenolate'], // check if split
    [/immunosuppression/g, 'immunosuppression'], // check if split
    [/pediat ric/g, 'pediatric'],
    [/adoles cent/g, 'adolescent'],
    [/cou nseling/g, 'counseling'],
    [/monit or/g, 'monitor'],
    [/leaflet/g, 'leaflet'], // check if split
    [/ambigu ous/g, 'ambiguous'],
    [/incomplete/g, 'incomplete'],
    [/re lative/g, 'relative'],
    [/absol ute/g, 'absolute'],
    [/contraind icated/g, 'contraindicated'],
    [/breast feeding/g, 'breastfeeding'],
    [/incomplet e/g, 'incomplete'],
    [/prevention_neural_tube_defect_preventi on/g, 'prevention_neural_tube_defect_prevention'],
    [/interact ions/g, 'interactions'],
    [/contraind ications/g, 'contraindications'],
    [/doseT ext/g, 'doseText'],
    [/UKTI S/g, 'UKTIS'],
    [/ANSM/g, 'ANSM'],
    [/hyp ertension/g, 'hypertension'],
    [/heart_f ailure/g, 'heart_failure'],
    [/titra tion/g, 'titration'],
    [/cardiol ogy/g, 'cardiology'],
    [/epilep sy/g, 'epilepsy'],
    [/trigemin al_neuralg ia/g, 'trigeminal_neuralgia'],
    [/bipolar_disorder_selecte d/g, 'bipolar_disorder_selected'],
    [/therape utic/g, 'therapeutic'],
    [/chemotherapy/g, 'chemotherapy'], // check if split
    [/cyto toxic/g, 'cytotoxic'],
    [/physi cian/g, 'physician'],
    [/guidance/g, 'guidance'],
    [/tri mester/g, 'trimester'],
    [/trimes ter/g, 'trimester'],
    [/minWeeks/g, 'minWeeks'], // check if split
    [/maxWeeks/g, 'maxWeeks'], // check if split
    [/strictly necessary/g, 'strictly necessary'], // check if split
    [/nd prescribed/g, 'and prescribed'], // fixed "nd"
    [/a nd prescribed/g, 'and prescribed'],
    [/rectal_use_only/g, 'rectal_use_only'],
    [/packaging/g, 'packaging'],
    [/ocular_use_only/g, 'ocular_use_only'],
    [/symptoma tic/g, 'symptomatic'],
    [/formu lation/g, 'formulation'],
    [/antibiotic/g, 'antibiotic'], // check if split
    [/eye_drops/g, 'eye_drops'],
    [/ophthalmic/g, 'ophthalmic'],
    [/capsule_or_tablet/g, 'capsule_or_tablet'],
    [/cephalosporin/g, 'cephalosporin'],
    [/renal function/g, 'renal function'],
    [/medical supervision/g, 'medical supervision'],
    [/cefuroxime/g, 'cefuroxime'],
    [/tablet_or_capsule/g, 'tablet_or_capsule'],
    [/arthritis/g, 'arthritis'],
    [/short est/g, 'shortest'],
    [/dura tion/g, 'duration'],
    [/contraindic ations/g, 'contraindications'],
    [/ambigu ous/g, 'ambiguous'],
    [/betamethasone/g, 'betamethasone'],
    [/obstetric/g, 'obstetric'],
    [/mycophenolate_mofetil/g, 'mycophenolate_mofetil'],
    [/transplant/g, 'transplant'],
    [/blood_counts/g, 'blood_counts'],
    [/contraception/g, 'contraception'],
    [/testing/g, 'testing'],
    [/symptoms/g, 'symptoms'],
    [/compatible/g, 'compatible'],
    [/desogestrel/g, 'desogestrel'],
    [/contraceptive/g, 'contraceptive'],
    [/enzyme - inducer/g, 'enzyme-inducer'],
    [/antiepileptics/g, 'antiepileptics'],
    [/efficacy/g, 'efficacy'],
    [/imiglucerase/g, 'imiglucerase'],
    [/statin/g, 'statin'],
    [/antiplatelet/g, 'antiplatelet'],
    [/vaccine/g, 'vaccine'],
    [/hpv_prevention/g, 'hpv_prevention'],
    [/schedule/g, 'schedule'],
    [/postpone/g, 'postpone'],
    [/emerg ency/g, 'emergency'],
    [/max_daily_dose/g, 'max_daily_dose'],
    [/medical advice/g, 'medical advice'],
    [/effervescent_tablet/g, 'effervescent_tablet'],
    [/dissolve_in_water/g, 'dissolve_in_water'],
    [/sodium/g, 'sodium'],
    [/restricted/g, 'restricted'],
    [/hypertension/g, 'hypertension'],
    [/heart failure/g, 'heart failure'],
    [/avoid_other_paracetamol/g, 'avoid_other_paracetamol'],
    [/suspension/g, 'suspension'],
    [/concentration/g, 'concentration'],
    [/drowsiness/g, 'drowsiness'],
    [/antihistamine/g, 'antihistamine'],
    [/opioid/g, 'opioid'],
    [/paracetamol/g, 'paracetamol'],
    [/abuse - risk/g, 'abuse-risk'],
    [/ear_drops/g, 'ear_drops'],
    [/steroid/g, 'steroid'],
    [/activeSubstances/g, 'activeSubstances'],
    [/dosage/g, 'dosage'],
    [/posology/g, 'posology'],
    [/indications/g, 'indications'],
    [/administra tion/g, 'administration'],
    [/indications/g, 'indications'],
    [/ta blet/g, 'tablet'],
    [/stre ngth/g, 'strength'],
    [/activeSubstances/g, 'activeSubstances'],
    [/activeSub stances/g, 'activeSubstances'],
    [/active Substances/g, 'activeSubstances'],
    [/activeS ubstances/g, 'activeSubstances'],
];

data.forEach(p => {
    let content = p.content;
    corrections.forEach(([regex, replacement]) => {
        content = content.replace(regex, replacement);
    });
    p.content = content;
});

fs.writeFileSync(filepath, JSON.stringify(data, null, 2));
console.log('Cleanup completed.');
